import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations';

enum PriceType {
  WHITERABBIT = "WHITERABBIT",
  RIGHTSHOLDER = "RIGHTSHOLDER"
}

export enum ApprovalStatus {
  APPROVED = "APPROVED",
  PENDING = "PENDING",
  REJECTED = "REJECTED",
}

export enum ActiveStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}

export class MovieResponse {
  success!: boolean;
  message!: string;
  movies!: Movie[];
}

export class Pricing {
    @attribute()
    type!: PriceType;

    @attribute()
    amount!: number;

    @attribute()
    region!: string;
}

export class RightsHolder {
    @attribute()
    name!: string;

    @attribute()
    contact!: string;

    @attribute()
    address!: string;

    @attribute()
    movies!: Array<Movie>;

    @attribute()
    status!: ApprovalStatus;
}

export class MovieRecord {
    @attribute()
    source!: string;

    @attribute()
    value!: string;
}

@table('movies')
export class Movie {
    @autoGeneratedHashKey()
    id!: string;

    @attribute()
    IMDB!: string;

    @attribute()
    ISAN!: string;

    @attribute()
    ownerAddress!: string;

    @attribute()
    payoutAddress!: string;

    @attribute()
    record!: MovieRecord;

    @attribute()
    chainTitle!: Array<string>;

    @attribute()
    rightsHolder!: RightsHolder;

    @attribute()
    pricing!: Array<Pricing>;

    @attribute()
    status!: ActiveStatus
}