name: Backend CI

on:
  pull_request:
    branches:
      - master
    paths:
      - 'backend/*'
      - '.github/workflows/backend.yml'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint Code
      run: |
        cd backend
        npm ci
        npm run lint

    - name: Test Code
      run: | 
        cd backend
        npm run test
