name: Common CI

on:
  push:
    paths:
      - 'common/**'
      - '.github/workflows/common-ci.yml'

defaults:
  run:
    working-directory: common

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('common/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install and build deps
      run: npm ci

    - name: Lint Code
      run: npm run lint

    - name: Test Code
      run: npm test

    - name: Test build
      run: ./node_modules/.bin/tsc
