name: Frontend CD

on:
  push:
    branches:
      - master
      - fix/cd
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-cd.yml'

jobs:
  CD:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
       cd frontend/
       npm install

    - name: Build Code
      run: |
       cd frontend/
       npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Copy files to AWS S3
      run: |
        aws s3 sync ./frontend/build s3://dashboard.whiterabbit.one  --acl public-read

    - name: Invalidate AWS CloudFront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id E2EJGKCLCBMRN1 --paths '/*'